// Données d'employés de test pour HRnet
export const mockEmployees = [
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1985-03-15",
    startDate: "2020-01-15",
    street: "123 Main Street",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    department: "Engineering"
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    dateOfBirth: "1990-07-22",
    startDate: "2019-06-10",
    street: "456 Oak Avenue",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90210",
    department: "Marketing"
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    dateOfBirth: "1988-11-08",
    startDate: "2021-03-20",
    street: "789 Pine Road",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    department: "Sales"
  },
  {
    firstName: "Sarah",
    lastName: "Williams",
    dateOfBirth: "1992-04-12",
    startDate: "2020-09-05",
    street: "321 Elm Street",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    department: "Human Resources"
  },
  {
    firstName: "David",
    lastName: "Brown",
    dateOfBirth: "1987-09-30",
    startDate: "2018-12-01",
    street: "654 Maple Drive",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85001",
    department: "Engineering"
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    dateOfBirth: "1991-12-03",
    startDate: "2021-01-15",
    street: "987 Cedar Lane",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19101",
    department: "Marketing"
  },
  {
    firstName: "Robert",
    lastName: "Miller",
    dateOfBirth: "1986-06-18",
    startDate: "2019-11-20",
    street: "147 Birch Court",
    city: "San Antonio",
    state: "TX",
    zipCode: "78201",
    department: "Sales"
  },
  {
    firstName: "Lisa",
    lastName: "Wilson",
    dateOfBirth: "1993-01-25",
    startDate: "2020-04-10",
    street: "258 Spruce Way",
    city: "San Diego",
    state: "CA",
    zipCode: "92101",
    department: "Human Resources"
  },
  {
    firstName: "James",
    lastName: "Taylor",
    dateOfBirth: "1989-08-14",
    startDate: "2018-07-01",
    street: "369 Willow Street",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    department: "Engineering"
  },
  {
    firstName: "Amanda",
    lastName: "Anderson",
    dateOfBirth: "1994-05-07",
    startDate: "2021-08-15",
    street: "741 Aspen Avenue",
    city: "San Jose",
    state: "CA",
    zipCode: "95101",
    department: "Marketing"
  },
  {
    firstName: "Christopher",
    lastName: "Thomas",
    dateOfBirth: "1984-10-20",
    startDate: "2017-05-12",
    street: "852 Poplar Road",
    city: "Austin",
    state: "TX",
    zipCode: "73301",
    department: "Sales"
  },
  {
    firstName: "Jessica",
    lastName: "Jackson",
    dateOfBirth: "1990-02-28",
    startDate: "2019-02-25",
    street: "963 Sycamore Lane",
    city: "Jacksonville",
    state: "FL",
    zipCode: "32099",
    department: "Human Resources"
  },
  {
    firstName: "Daniel",
    lastName: "White",
    dateOfBirth: "1988-12-11",
    startDate: "2020-06-08",
    street: "159 Magnolia Drive",
    city: "Fort Worth",
    state: "TX",
    zipCode: "76101",
    department: "Engineering"
  },
  {
    firstName: "Ashley",
    lastName: "Harris",
    dateOfBirth: "1992-07-04",
    startDate: "2021-10-12",
    street: "357 Redwood Court",
    city: "Columbus",
    state: "OH",
    zipCode: "43201",
    department: "Marketing"
  },
  {
    firstName: "Matthew",
    lastName: "Clark",
    dateOfBirth: "1987-03-19",
    startDate: "2018-09-30",
    street: "486 Sequoia Way",
    city: "Charlotte",
    state: "NC",
    zipCode: "28201",
    department: "Sales"
  },
  {
    firstName: "Nicole",
    lastName: "Lewis",
    dateOfBirth: "1993-11-02",
    startDate: "2020-12-03",
    street: "753 Cypress Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94101",
    department: "Human Resources"
  },
  {
    firstName: "Andrew",
    lastName: "Robinson",
    dateOfBirth: "1986-04-16",
    startDate: "2019-04-18",
    street: "951 Hickory Avenue",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46201",
    department: "Engineering"
  },
  {
    firstName: "Stephanie",
    lastName: "Walker",
    dateOfBirth: "1991-08-29",
    startDate: "2021-05-22",
    street: "264 Walnut Road",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    department: "Marketing"
  },
  {
    firstName: "Ryan",
    lastName: "Perez",
    dateOfBirth: "1989-01-13",
    startDate: "2018-11-07",
    street: "573 Chestnut Lane",
    city: "Denver",
    state: "CO",
    zipCode: "80201",
    department: "Sales"
  },
  {
    firstName: "Lauren",
    lastName: "Hall",
    dateOfBirth: "1994-06-26",
    startDate: "2020-07-14",
    street: "842 Beech Court",
    city: "Washington",
    state: "DC",
    zipCode: "20001",
    department: "Human Resources"
  },
  {
    firstName: "Kevin",
    lastName: "Young",
    dateOfBirth: "1985-09-08",
    startDate: "2017-12-01",
    street: "135 Alder Drive",
    city: "Boston",
    state: "MA",
    zipCode: "02101",
    department: "Engineering"
  },
  {
    firstName: "Rachel",
    lastName: "Allen",
    dateOfBirth: "1990-12-21",
    startDate: "2019-08-25",
    street: "468 Fir Way",
    city: "Nashville",
    state: "TN",
    zipCode: "37201",
    department: "Marketing"
  },
  {
    firstName: "Steven",
    lastName: "King",
    dateOfBirth: "1988-05-17",
    startDate: "2020-03-11",
    street: "791 Hemlock Street",
    city: "Detroit",
    state: "MI",
    zipCode: "48201",
    department: "Sales"
  },
  {
    firstName: "Megan",
    lastName: "Wright",
    dateOfBirth: "1993-02-09",
    startDate: "2021-09-28",
    street: "324 Larch Avenue",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    department: "Human Resources"
  },
  {
    firstName: "Brian",
    lastName: "Lopez",
    dateOfBirth: "1987-07-31",
    startDate: "2018-06-15",
    street: "657 Spruce Road",
    city: "Memphis",
    state: "TN",
    zipCode: "38101",
    department: "Engineering"
  },
  {
    firstName: "Kimberly",
    lastName: "Hill",
    dateOfBirth: "1992-10-05",
    startDate: "2019-10-08",
    street: "189 Pine Lane",
    city: "Oklahoma City",
    state: "OK",
    zipCode: "73101",
    department: "Marketing"
  },
  {
    firstName: "Timothy",
    lastName: "Scott",
    dateOfBirth: "1986-01-24",
    startDate: "2020-11-20",
    street: "423 Oak Court",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89101",
    department: "Sales"
  },
  {
    firstName: "Heather",
    lastName: "Green",
    dateOfBirth: "1994-04-03",
    startDate: "2021-02-14",
    street: "756 Maple Drive",
    city: "Louisville",
    state: "KY",
    zipCode: "40201",
    department: "Human Resources"
  },
  {
    firstName: "Jeffrey",
    lastName: "Adams",
    dateOfBirth: "1989-11-12",
    startDate: "2018-03-05",
    street: "918 Elm Way",
    city: "Baltimore",
    state: "MD",
    zipCode: "21201",
    department: "Engineering"
  },
  {
    firstName: "Michelle",
    lastName: "Baker",
    dateOfBirth: "1991-06-30",
    startDate: "2019-07-22",
    street: "247 Birch Street",
    city: "Milwaukee",
    state: "WI",
    zipCode: "53201",
    department: "Marketing"
  },
  {
    firstName: "Mark",
    lastName: "Gonzalez",
    dateOfBirth: "1987-12-18",
    startDate: "2020-05-09",
    street: "539 Cedar Avenue",
    city: "Albuquerque",
    state: "NM",
    zipCode: "87101",
    department: "Sales"
  },
  {
    firstName: "Tiffany",
    lastName: "Nelson",
    dateOfBirth: "1993-03-27",
    startDate: "2021-12-01",
    street: "872 Willow Road",
    city: "Tucson",
    state: "AZ",
    zipCode: "85701",
    department: "Human Resources"
  }
];